WebApplication/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication.Models;

namespace WebApplication.Controllers
{ // [Route("address")]
    [Authorize]
    public class AddressController : Controller
    {
        AddressUserContext db;

        public AddressController(AddressUserContext db)
        {
            this.db = db;
        }

        [HttpGet("address")]
        public ActionResult Index(string sortBy, string search)
        {
            IEnumerable<Address> list;
            if (!UserIsAdmin())
            {
             

                list = GetDataAddressesFromUser(GetUserId());
            }
            else
            {
                list = GetAllAddresses();
            }

            if (!String.IsNullOrEmpty(search))
            {
                list = SearchBy(search).ToList();
            }

            if ( String.IsNullOrEmpty(sortBy))
            {
                sortBy = "address_id";
            }
             
            ViewBag.SortParam = sortBy;
            list = list.OrderBy(o => o.GetType().GetProperty(sortBy)?.GetValue(o)).ToList();

            return View(list);
        }

        [HttpGet("address/{id:int}")]
        public ActionResult GetAddress(int id)
        {
            if (!UserHasAddress(id) && !UserIsAdmin())
            {
                return NotFound();
            }

            var addressItem = GetAddressById(id);
            if (addressItem == null)
            {
                return NotFound();
            }

            return View(addressItem);
            //    return Content(db.Addresses.FirstOrDefault(s => s.address_id == id).ToString());
        }

        [HttpGet]
        public ActionResult EditAddress(int? id)
        {
            if (!(UserHasAddress(id) || UserIsAdmin()))
            {
                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }

            Address address = GetAddressById(id);
            if (address != null)
            {
                return View(address);
            }

            return NotFound();
        }

        [HttpPost]
        public ActionResult EditAddress(Address curAddress)
        {
            if (ModelState.IsValid)
            {
                Address oldAddress = GetAddressById(curAddress.address_id);
                oldAddress.address_id = curAddress.address_id;
                oldAddress.surname = curAddress.surname;
                oldAddress.address = curAddress.address;
                oldAddress.building = curAddress.building;
                oldAddress.rent = curAddress.rent;

                db.Entry(oldAddress).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(curAddress);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Address a)
        {
            /*if (db.Addresses.ToList().Exists(x => x.address_id == a.address_id))
            {
                return RedirectToAction("Index");
            }*/

            if (ModelState.IsValid )
            {

                Address address = new Address()
                {
                    surname = a.surname, address = a.address, building = a.building, flat = a.flat, rent = a.rent
                };
              
                db.Addresses.Add(address);
                db.SaveChanges();
             
             
                db.AddressUsers.Add(new AddressUser
                {
                   address_id = address.address_id,user_id = GetUserId()
                });
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(a);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (!(UserHasAddress(id) || UserIsAdmin()))
            {
                return NotFound();
            }

            Address b = GetAddressById(id);
            if (b == null)
            {
                return NotFound();
            }

            return View(b);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Address b = GetAddressById(id);
            if (b == null)
            {
                return NotFound();
            }

            db.Addresses.Remove(b);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public HashSet<Address> SearchBy(string s)
        {
            var searchingObject = new HashSet<Address>();
            IEnumerable<Address> list;
            if (UserIsAdmin())
            {
                list = GetAllAddresses();
            }
            else
            {
                list = GetDataAddressesFromUser(GetUserId());
            }

            foreach (var obj in list)
            {
                var properties = obj.GetType().GetProperties();
                foreach (var prop in properties)
                {
                    if (Convert.ToString(prop.GetValue(obj)).Contains(s))
                    {
                        searchingObject.Add(obj);
                    }
                }
            }

            return searchingObject;
        }

        public int GetUserId()
        {
            string userEmail = User.Identity.Name;
            User user = db.Users.FirstOrDefault(u => u.email == userEmail);
            Debug.Assert(user != null, nameof(user) + " != null");
            return user.user_id;
        }

        public IEnumerable<Address> GetDataAddressesFromUser(int id)
        {
            var list = (from r in db.Addresses
                join c in db.AddressUsers on r.address_id equals c.address_id
                where c.user_id == id
                select r).AsEnumerable();
            return list;
        }

        public bool UserHasAddress(int? id)
        {
            AddressUser addressUser = db.AddressUsers.FirstOrDefault(u => u.address_id == id);
            if (addressUser == null)
            {
                return false;
            }

            return true;
        }

        public Address GetAddressById(int? id)
        {
            return db.Addresses.Find(id);
        }

        public IEnumerable<Address> GetAllAddresses()
        {
            return db.Addresses.ToList();
        }

        public bool UserIsAdmin()
        {
            return User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value == "admin";
        }
    }
}

WebApplication/Views/Address/Create.cshtml
@model Address


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
<h2>New Address</h2>
 
@using (Html.BeginForm()) 
{ 
    @Html.LabelFor(model => model.surname, "surname")
    <br />
    @Html.EditorFor(model => model.surname)
    <span asp-validation-for="surname"></span>
    <br /><br />
    @Html.LabelFor(model => model.address, "address")
    <br />
    @Html.EditorFor(model => model.address)
    <span asp-validation-for="address"></span>
    <br /><br />
    @Html.LabelFor(model => model.building, "building")
    <br />
    @Html.EditorFor(model => model.building)
    <span asp-validation-for="building"></span>
    <br /><br />
    @Html.LabelFor(model => model.flat, "flat")
    <br />
    @Html.EditorFor(model => model.flat)
    <span asp-validation-for="flat"></span>
    <br /><br />
    @Html.LabelFor(model => model.rent, "rent")
    <br />
    @Html.EditorFor(model => model.rent)
    <span asp-validation-for="rent"></span>
    <br /><br />
    <input type="submit" value="add" />
}
@section scripts{
 
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

WebApplication/Views/Address/Delete.cshtml
@model Address

@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Address Delete</h2>
<dl>
    <dt>Surname</dt>
    <dd>
        @Html.DisplayFor(model => model.surname)
    </dd>
 
    <dt>address</dt>
    <dd>
        @Html.DisplayFor(model => model.address)
    </dd>
 
    <dt>building</dt>
    <dd>
        @Html.DisplayFor(model => model.building)
    </dd>
     <dt>flat</dt>
    <dd>
        @Html.DisplayFor(model => model.flat)
    </dd>
     <dt>rent</dt>
        <dd>
            @Html.DisplayFor(model => model.rent)
        </dd>
</dl>
 
@using (Html.BeginForm())
{
    <input type="submit" value="delete"  />
}

WebApplication/Views/Address/EditAddress.cshtml
@{
    ViewBag.Title = "Edit Address";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WebApplication.Models.Address
<h2>Address № @Model.address_id</h2>
@using (Html.BeginForm("EditAddress", "address", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.address_id)
        <p>
            @Html.LabelFor(m => m.surname, "surname")
            <br />
            @Html.EditorFor(m => m.surname)
              <span asp-validation-for="surname"></span>
        </p>
        <p>
            @Html.LabelFor(m => m.address, "address")
            <br />
            @Html.EditorFor(m => m.address)
              <span asp-validation-for="address"></span>
 
        </p>
        <p>
            @Html.LabelFor(m => m.building, "building")
            <br />
            @Html.EditorFor(m => m.building)
              <span asp-validation-for="building"></span>
        </p>
        <p>
            @Html.LabelFor(m => m.flat, "flat")
            <br />
            @Html.EditorFor(m => m.flat)
              <span asp-validation-for="flat"></span>
        </p>
        <p>
                    @Html.LabelFor(m => m.rent, "rent")
                    <br />
                    @Html.EditorFor(m => m.rent)
                      <span asp-validation-for="rent"></span>
                </p>
        <p><input type="submit" value="save" /></p>
    </fieldset>
}
@section scripts{
 
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

WebApplication/Views/Address/GetAddress.cshtml
@using System.Security.Claims
@model Address

@{
    ViewBag.Title = "GetAddress";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;    
}
</style>
<div>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr class="header">

            <td>
                <p>id</p>
            </td>
            <td>
                <p>surname</p>
            </td>
            <td>
                <p>name of address</p>
            </td>
            <td>
                <p>number of building</p>
            </td>
            <td>
                <p>number of flat</p>
            </td>
            <td>
                <p>rent</p>
            </td>
            @if (User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value == "admin")
            {
                <td></td>
            }

        </tr>

        <tr>
            <td>
                <p>@Model.address_id</p>
            </td>
            <td>
                <p>@Model.surname</p>
            </td>
            <td>
                <p>@Model.address</p>
            </td>
            <td>
                <p>@Model.building</p>
            </td>
            <td>
                <p>@Model.flat</p>
            </td>
            <td>
                <p>@Model.rent</p>
            </td>
            @if (User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value == "admin")
            {
                <td>
                    @Html.ActionLink("Edit", "EditAddress", new {id = Model.address_id}) |
                    @Html.ActionLink("Delete", "Delete", new {id = Model.address_id})
                </td>
            }

        </tr>

    </table>
</div>

WebApplication/Views/Address/Index.cshtml
@using System.Security.Claims
@model IEnumerable<Address>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
.logoutLblPos{

   position:fixed;
   right:10px;
   top:5px;
}
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;    
}
</style>
<h3>addresses</h3>
<div>
    <div style="padding-bottom: 30px">
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        @using (Html.BeginForm("Index", "Address", FormMethod.Get))
        {
            <p>
                Find: @Html.TextBox("search", ViewBag.CurrentFilter as string)
                <input type="submit" value="Search"/>
            </p>
        }

        @using (Html.BeginForm("Index", "Address", FormMethod.Get))
        {
            <fieldset>
                Sort Type
                <select id="sortBy" name="sortBy" onchange="this.form.submit()">

                    @if (ViewBag.SortParam == "address_id")
                    {
                        <option value="address_id" selected="selected">address_id</option>
                    }
                    else
                    {
                        <option value="address_id">address_id</option>
                    }
                    @if (ViewBag.SortParam == "surname")
                    {
                        <option value="surname" selected="selected">surname</option>
                    }
                    else
                    {
                        <option value="surname">surname</option>
                    }
                    @if (ViewBag.SortParam == "address")
                    {
                        <option value="address" selected="selected">address</option>
                    }else{
                    <option value="address">address</option>
                    }
                    @if (ViewBag.SortParam == "building")
                    {
                        <option value="building" selected="selected">building</option>
                    }
                    else
                    {
                        <option value="building">building</option>
                    }
                    @if (ViewBag.SortParam == "flat")
                    {
                        <option value="flat" selected="selected">flat</option>
                    }
                    else
                    {
                        <option value="flat">flat</option>
                    }
                    @if (ViewBag.SortParam == "rent")
                    {
                        <option value="rent" selected="selected">rent</option>
                    }
                    else
                    {
                        <option value="rent">rent</option>
                    }

                </select>
                <!--     <input type="submit" value="Submit"> -->

            </fieldset>
        }

    </div>
    <table>
        <tr>
            <td>
                <p>id</p>
            </td>
            <td>
                <p>surname</p>
            </td>
            <td>
                <p>name of address</p>
            </td>
            <td>
                <p>number of building</p>
            </td>
            <td>
                <p>number of flat</p>
            </td>
            <td>
                <p>rent</p>
            </td>
            @if (User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value == "admin")
            {
                <td></td>
            }
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.address_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.building)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.flat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.rent)
                </td>
                @if (User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value == "admin")
                {
                    <td>
                        @Html.ActionLink("Edit", "EditAddress", new {id = item.address_id}) |
                        @Html.ActionLink("Delete", "Delete", new {id = item.address_id})
                    </td>
                }
            </tr>
        }
        @using (Html.BeginForm("Logout", "Account", FormMethod.Get))
        {
            <label class="logoutLblPos">
                <input name="submit2" type="submit" id="submit2" value="log out">
            </label>
        }
    </table>
</div>